---
- name: create weave-net secret file and kubernetes secret
  shell: |
    /bin/openssl rand -base64 32 > $ANSIBLE_WEAVE_NET_WORKDIR/weave-passwd \
    && kubectl create secret -n kube-system generic weave-passwd \
    --from-file=$ANSIBLE_WEAVE_NET_WORKDIR/weave-passwd
  environment:
    KUBECONFIG: "{{ weave_net_project_dir }}/master/admin.conf"
    ANSIBLE_WEAVE_NET_WORKDIR: "{{ weave_net_project_dir }}/weave-net"
  delegate_to: localhost
  connection: local
  run_once: true
  become: no
  when: weave_net_encryption is true

- name: download weave-net manifests
  get_url:
    url: https://cloud.weave.works/k8s/net?k8s-version={{ item }}
    dest: "{{ weave_net_project_dir }}/weave-net/weave-net.yml"
  with_items: "{{ weave_net_k8s_version }}{{ '&password-secret=weave-passwd' if weave_net_encryption is true }}{{ weave_net_env if weave_net_env | length }}"
  delegate_to: localhost
  connection: local
  run_once: true
  become: no

- name: install pod network
  shell: |
    kubectl apply -f $ANSIBLE_WEAVE_NET_WORKDIR/weave-net.yml
  environment:
    KUBECONFIG: "{{ weave_net_project_dir }}/master/admin.conf"
    ANSIBLE_WEAVE_NET_WORKDIR: "{{ weave_net_project_dir }}/weave-net"
  delegate_to: localhost
  connection: local
  run_once: true
  become: no
